upstream notes_backend {
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
}

server {
    listen      8081;
    server_name localhost;

    location /api/ {
        proxy_pass http://notes_backend;
    }
}