# ограничение кол-ва запросов к /api (3 запроса в секунду с одного IP)
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;

upstream notes_backend {
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
}


# редирект HTTP -> HTTPS
server {
    listen      80;
    server_name notes.local site2.local;

    return 301 https://$host$request_uri;
}


# неизвестные домены через HTTP-запросы
server {
    listen      80 default_server;
    server_name _;

    error_page 404 /404.html;

    location = /404.html {
        root     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors;
        internal;
    }

    location /error-assets/ {
        alias /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors/assets/;
    }

    location / {
        return 404;
    }
}


# неизвестные домены через HTTPS-запросы
server {
    listen      443 ssl default_server;
    server_name _;

    # самоподписанный сертификат и приватный ключ сертификата
    ssl_certificate     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.crt;
    ssl_certificate_key /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.key;

    error_page 404 /404.html;

    location = /404.html {
        root     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors;
        internal;
    }

    location /error-assets/ {
        alias /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors/assets/;
    }

    location / {
        return 404;
    }
}


# notes.local
server {
    listen      443         ssl;
    server_name notes.local;

    # самоподписанный сертификат и приватный ключ сертификата
    ssl_certificate     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.crt;
    ssl_certificate_key /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.key;

    root  /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/frontend;
    index index.html;

    error_page 404 /404.html;

    location = /404.html {
        root     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors;
        internal;
    }

    location /error-assets/ {
        alias /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors/assets/;
    }

    # api
    location /api/ {
        limit_req        zone=api_limit;
        limit_req_status 429;

        proxy_pass http://notes_backend;
    }

    # документация
    location = /docs {
        return 301 /docs/;
    }

    location /docs/ {
        alias /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/docs/;
        index index.html;
    }

    # админка
    location = /admin {
        return 301 /admin/;
    }

    location /admin/ {
        # включаем Basic Auth
        auth_basic           "Admin panel";
        # файл пользователей и хешей их паролей
        auth_basic_user_file /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/.htpasswd;

        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}


# site2.local
server {
    listen      443         ssl;
    server_name site2.local;

    # самоподписанный сертификат и приватный ключ сертификата
    ssl_certificate     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.crt;
    ssl_certificate_key /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/certs/lab1.key;

    root  /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/site2;
    index index.html;

    error_page 404 /404.html;

    location = /404.html {
        root     /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors;
        internal;
    }

    location /error-assets/ {
        alias /Users/denisbaranov/cs_projects/3s/CloudTech/lab1/nginx/errors/assets/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}