# Ограничение кол-ва запросов к API
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;


# Backend группа
upstream notes_backend {
    server backend:8000;
}


# Основной сервер
server {
    listen      80;
    server_name notes.local;

    # Статические файлы frontend
    root  /usr/share/nginx/html;
    index index.html;


    # Проверка работы NGINX для HEALTHCHECK в Docker
    location = /healthz {
        return 200 "ok";
    }


    # API
    location /api/ {
        limit_req        zone=api_limit;
        limit_req_status 429;

        proxy_pass http://notes_backend;
    }


    # Frontend
    location / {
        try_files $uri $uri/ =404;
    }
}